# Generated by Django 2.1.7 on 2019-03-13 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hierarchy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eat_better.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Nutriments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fat', models.DecimalField(decimal_places=1, max_digits=4)),
                ('sugars', models.DecimalField(decimal_places=1, max_digits=4)),
                ('saturated_fat', models.DecimalField(decimal_places=1, max_digits=4)),
                ('salt', models.DecimalField(decimal_places=3, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('nutriscore', models.CharField(max_length=1)),
                ('url', models.CharField(max_length=255)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eat_better.Brand')),
                ('categories', models.ManyToManyField(through='eat_better.Hierarchy', to='eat_better.Category')),
                ('nutriments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eat_better.Nutriments')),
            ],
        ),
        migrations.AddField(
            model_name='hierarchy',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eat_better.Product'),
        ),
    ]
