# Generated by Django 2.1.7 on 2019-03-08 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eat_better', '0004_auto_20190308_1022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nutriments',
            old_name='fats',
            new_name='fat',
        ),
    ]
