# Generated by Django 2.1.7 on 2019-03-12 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eat_better', '0006_auto_20190312_1504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='categories',
        ),
    ]
