# Generated by Django 2.1.7 on 2019-03-13 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eat_better', '0008_auto_20190313_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutriments',
            name='fat',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='nutriments',
            name='salt',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
        migrations.AlterField(
            model_name='nutriments',
            name='saturated_fat',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='nutriments',
            name='sugars',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
    ]
